DELETE FROM BANK_CONNECTION_DATA;
DELETE FROM BANK_ACCOUNT;
DELETE FROM USERS;
DELETE FROM BANK_API;
DELETE FROM BANKS;

INSERT INTO BANKS (ID, NAME) values(1, 'Full-api-bank');
INSERT INTO BANKS (ID, NAME) values(2, 'Non-balance-bank');

INSERT INTO BANK_API (BANK_ID, BANK_API_TYPE, URL) VALUES (1, 'DO_LOGIN', 'http://full-bank.com/login');
INSERT INTO BANK_API (BANK_ID, BANK_API_TYPE, URL) VALUES (1, 'GET_TRANSACTIONS', 'http://full-bank.com/transactions');
INSERT INTO BANK_API (BANK_ID, BANK_API_TYPE, URL) VALUES (1, 'GET_BALANCE', 'http://full-bank.com/balance');

INSERT INTO BANK_API (BANK_ID, BANK_API_TYPE, URL) VALUES (2, 'DO_LOGIN', 'http://non-balance-bank.com/login');
INSERT INTO BANK_API (BANK_ID, BANK_API_TYPE, URL) VALUES (2, 'GET_TRANSACTIONS', 'http://non-balance-bank.com/transactions');

INSERT INTO USERS (ID, USERNAME, EMAIL) values(1, 'regular-user', 'regular-user@email.com');
INSERT INTO USERS (ID, USERNAME, EMAIL) values(2, 'without-bank-account-user', 'noBanks@email.com');

INSERT INTO BANK_ACCOUNT (USER_ID, ID, NAME, MARKER_COLOR) VALUES (1, 1, 'default-mapping', 'RED');
INSERT INTO BANK_ACCOUNT (USER_ID, ID, NAME, MARKER_COLOR) VALUES (1, 2, 'mapping-01', 'GREEN');

INSERT INTO BANK_CONNECTION_DATA (BANK_ID, BANK_ACCOUNT_ID, BANK_LOGIN_TOKEN, CONSENT_SCOPE, EXPIRY_DATE)
VALUES (1, 1, 'valid-token-01', 'all', '2099-01-01');

INSERT INTO BANK_CONNECTION_DATA (BANK_ID, BANK_ACCOUNT_ID, BANK_LOGIN_TOKEN, CONSENT_SCOPE, EXPIRY_DATE)
VALUES (2, 2, 'expired-token-01', 'transactions,balance', '2000-01-01');

