INSERT INTO TRANSACTIONS (UUID, ACCOUNT_NUMBER, DIRECTION, AMOUNT)
VALUES(random_uuid(), '123', 'PAY', 200);

INSERT INTO TRANSACTIONS (UUID, ACCOUNT_NUMBER, DIRECTION, AMOUNT)
VALUES(random_uuid(), '456', 'RECEIVE', 100);

INSERT INTO TRANSACTIONS (UUID, ACCOUNT_NUMBER, DIRECTION, AMOUNT)
VALUES(random_uuid(), '789', 'PAY', 3.50);