INSERT INTO USERS (ID, USERNAME, EMAIL)
VALUES(1, 'John Snow', 'iknownothing@nightwatch.com');

INSERT INTO BANKS (ID, NAME, API_URL)
VALUES(1, 'Iron Bank', 'http://iron-bank.bv/api');

INSERT INTO ACCOUNTS (ACCOUNT_NUMBER, BANK_ID, USER_ID, BALANCE)
VALUES('1234', 1, 1, 12.23);


INSERT INTO TRANSACTIONS (UUID, ACCOUNT_NUMBER, DIRECTION, AMOUNT)
VALUES(random_uuid(), '123', 'PAY', 200);

INSERT INTO TRANSACTIONS (UUID, ACCOUNT_NUMBER, DIRECTION, AMOUNT)
VALUES(random_uuid(), '456', 'RECEIVE', 100);

INSERT INTO TRANSACTIONS (UUID, ACCOUNT_NUMBER, DIRECTION, AMOUNT)
VALUES(random_uuid(), '789', 'PAY', 3.50);
